- name: install nodejs yum repositories
  shell: curl -sL https://rpm.nodesource.com/setup_5.x | bash -
  args:
    creates: /etc/yum.repos.d/nodesource-el.repo

- name: install nodejs
  yum:
    name: "{{item}}"
  with_items:
  - nodejs

- name: install catchmail and maildev
  npm:
    name: "{{ item }}"
    global: yes
  with_items:
  - catchmail
  - maildev

- name: link catchmail to sendmail
  file:
    src: /usr/bin/catchmail
    dest: /usr/sbin/sendmail
    state: link

- name: install supervisor configuration
  template:
    src: maildev.ini.j2
    dest: /etc/supervisord.d/maildev.ini

- name: reload supervisor
  supervisorctl:
    name: maildev
    state: started
